# NN by Hand

In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse

We're going to make a very simple neural network by hand.

Let's imagine that we have just a five-neuron network: two input neurons, two hidden-layer neurons, and a single output neuron.

We'll start by giving ourselves a regression problem.

![example](./images/one-hidden-layer-simplest-neural-network.jpg)

In [2]:
X, y = make_regression(n_features=2,
                       n_informative=1,
                       noise=100,
                       random_state=42)

Let's first check to see how a vanilla linear regression model does:

In [3]:
X[:5]

array([[-1.41537074, -0.42064532],
       [ 0.52194157,  0.29698467],
       [-0.88951443, -0.81581028],
       [-0.88385744,  0.15372511],
       [ 0.73846658,  0.17136828]])

In [4]:
X.shape

(100, 2)

In [5]:
simple_lr = LinearRegression().fit(X, y)

simple_lr.score(X, y)

0.4144461358278726

In [6]:
mse(y, simple_lr.predict(X), squared=False)

101.32961290191164

## Input Neurons

We have just two features, so we'll have two input neurons.

In [7]:
n_samples = X.shape[0]
n_features = X.shape[1]

# Initial inputs
input1 = X[:, 0].reshape(-1, 1)
input2 = X[:, 1].reshape(-1, 1)

In [8]:
input1.shape

(100, 1)

## Weights for the Connections Between the Input Neurons and the Hidden Neurons

We'll just start by setting our weights randomly. The idea will be that we'll be able to use gradient descent to improve their values during network training.

In [9]:
# Four weights to optimize for between input
# and hidden layers

# For simplicity let's assume biases of 0
# throughout

np.random.seed(42)


in_hid_weights1 = np.random.rand(2)
in_hid_weights2 = np.random.rand(2)

In [10]:
in_hid_weights1

array([0.37454012, 0.95071431])

## Hidden Neurons

Each neuron in the hidden layer will take the two inputs and multiply them by a unique set of weights:

In [14]:
np.array([in_hid_weights1, input1], dtype=object)

array([array([0.37454012, 0.95071431]),
       array([[-1.41537074],
       [ 0.52194157],
       [-0.88951443],
       [-0.88385744],
       [ 0.73846658],
       [-0.26465683],
       [ 1.14282281],
       [ 0.36139561],
       [ 0.81252582],
       [-0.22346279],
       [-1.10633497],
       [-0.84679372],
       [-0.60063869],
       [ 0.00511346],
       [-0.23415337],
       [-1.60748323],
       [ 0.09707755],
       [ 0.32408397],
       [-0.39210815],
       [-0.07201012],
       [-0.46341769],
       [ 1.8861859 ],
       [ 1.57921282],
       [ 0.09965137],
       [ 0.81351722],
       [-1.1913035 ],
       [ 0.58685709],
       [-1.32818605],
       [-0.11564828],
       [ 0.49671415],
       [-0.21967189],
       [-1.55066343],
       [-1.72491783],
       [ 1.86577451],
       [-0.07710171],
       [-1.91877122],
       [ 0.64768854],
       [-0.676922  ],
       [ 1.15859558],
       [ 0.09176078],
       [-0.24538812],
       [ 0.24196227],
       [-2.6197451 ],
       

In [13]:
0.37454012 * -1.41537074

-0.5301131268040887

In [12]:
np.product(np.array([in_hid_weights1, input1], dtype=object), axis=0)

array([[-5.30113126e-01, -1.34561321e+00],
       [ 1.95488056e-01,  4.96217314e-01],
       [-3.33158840e-01, -8.45674094e-01],
       [-3.31040069e-01, -8.40295909e-01],
       [ 2.76585361e-01,  7.02070742e-01],
       [-9.91246018e-02, -2.51613038e-01],
       [ 4.28032993e-01,  1.08649800e+00],
       [ 1.35357153e-01,  3.43583972e-01],
       [ 3.04323518e-01,  7.72479924e-01],
       [-8.36957782e-02, -2.12449267e-01],
       [-4.14366833e-01, -1.05180849e+00],
       [-3.17158220e-01, -8.05058902e-01],
       [-2.24963286e-01, -5.71035795e-01],
       [ 1.91519466e-03,  4.86143639e-03],
       [-8.76998328e-02, -2.22612963e-01],
       [-6.02066962e-01, -1.52825731e+00],
       [ 3.63594369e-02,  9.22930150e-02],
       [ 1.21382448e-01,  3.08111266e-01],
       [-1.46860234e-01, -3.72782831e-01],
       [-2.69706795e-02, -6.84610528e-02],
       [-1.73568518e-01, -4.40577830e-01],
       [ 7.06452292e-01,  1.79322392e+00],
       [ 5.91478556e-01,  1.50138022e+00],
       [ 3.

In [15]:
in1_to_hid = (np.sum(np.product(np.array([in_hid_weights1, input1], dtype=object), axis=0), axis=1)).reshape(-1, 1)
in2_to_hid = (np.sum(np.product(np.array([in_hid_weights2, input2], dtype=object), axis=0), axis=1)).reshape(-1, 1)

In [16]:
-5.30113126e-01 + -1.34561321e+00

-1.875726336

In [17]:
in1_to_hid 

array([[-1.87572634],
       [ 0.69170537],
       [-1.17883293],
       [-1.17133598],
       [ 0.9786561 ],
       [-0.35073764],
       [ 1.51453099],
       [ 0.47894113],
       [ 1.07680344],
       [-0.29614505],
       [-1.46617532],
       [-1.12221712],
       [-0.79599908],
       [ 0.00677663],
       [-0.3103128 ],
       [-2.13032427],
       [ 0.12865245],
       [ 0.42949371],
       [-0.51964307],
       [-0.09543173],
       [-0.61414635],
       [ 2.49967621],
       [ 2.09285877],
       [ 0.13206341],
       [ 1.07811729],
       [-1.57878023],
       [ 0.77773496],
       [-1.76018444],
       [-0.1532634 ],
       [ 0.65827263],
       [-0.29112114],
       [-2.05502357],
       [-2.28595499],
       [ 2.47262593],
       [-0.10217938],
       [-2.54286004],
       [ 0.8583521 ],
       [-0.89709388],
       [ 1.53543392],
       [ 0.12160638],
       [-0.32520169],
       [ 0.32066157],
       [-3.47182879],
       [ 0.36668571],
       [ 1.21314071],
       [-1

In [18]:
in1_to_hid.shape

(100, 1)

For simplicity let's assume a **linear activation function**, $f(x)=x$, in the hidden nodes.

## Weights for the Connections Between the Hidden Neurons and the Output Neuron

Again we'll just set our weights randomly. Here there will be two weights: one governing the connection between each hidden neuron and the output neuron.

In [19]:
np.random.seed(42)

hid_out_weights = np.random.rand(2)

In [20]:
hid_out_weights

array([0.37454012, 0.95071431])

## Output Neuron

Now we need to take the contribution from each hidden neuron and create a linear sum with the predetermined weights, just as above in the hidden neurons.

In [21]:
joint_to_out = np.hstack((in1_to_hid, in2_to_hid))

In [22]:
joint_to_out

array([[-1.87572634, -0.55973272],
       [ 0.69170537,  0.39518338],
       [-1.17883293, -1.08555993],
       [-1.17133598,  0.20455469],
       [ 0.9786561 ,  0.22803162],
       [-0.35073764,  3.6195997 ],
       [ 1.51453099,  1.00056151],
       [ 0.47894113,  2.04659209],
       [ 1.07680344,  1.80468408],
       [-0.29614505,  0.95008649],
       [-1.46617532, -1.59173525],
       [-1.12221712, -2.01573513],
       [-0.79599908, -0.388143  ],
       [ 0.00677663, -0.31215394],
       [-0.3103128 , -0.31155491],
       [-2.13032427,  0.24568349],
       [ 0.12865245,  1.28892981],
       [ 0.42949371, -0.51241067],
       [-0.51964307, -1.94742972],
       [-0.09543173,  1.33535349],
       [-0.61414635, -0.61972443],
       [ 2.49967621,  0.23230239],
       [ 2.09285877,  1.02118888],
       [ 0.13206341, -0.6699511 ],
       [ 1.07811729, -1.63785259],
       [-1.57878023,  0.87364465],
       [ 0.77773496,  2.91473509],
       [-1.76018444,  0.26195388],
       [-0.1532634 ,

In [23]:
output = (np.sum(np.product([hid_out_weights, joint_to_out],dtype=object, axis=0), axis=1)).reshape(-1, 1)

In [24]:
output[:5]

array([[-1.23468067],
       [ 0.6347779 ],
       [-1.47357759],
       [-0.24423925],
       [ 0.5833389 ]])

Again we'll assume a linear activation.

## Error Calculation

Now we can compute a measure of error:

In [25]:
output = output.flatten()

np.sqrt(mse(y, output))

132.0854176645698

### Backpropagation

Now then: How do we make corrections to our weights to improve our model's performance? Our network looks like this:

![nn](images/SimpleNN.png)

Clearly our output is a function of these six weights. But what function, exactly?

- In the top hidden node we construct: <br/> $H_1 = w_1X_1 + w_3X_2$ <br/> and in the bottom node we construct: <br/> $H_2 = w_2X_1 + w_4X_2$.
<br/> <br/>
- In the output node we construct: <br/> $\hat{y} = w_5H_1 + w_6H_2$ <br/> i.e. <br/> $\hat{y} = w_5(w_1X_1 + w_3X_2) + w_6(w_2X_1 + w_4X_2)$ <br/> or <br/> $\hat{y} = X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)$.

#### Loss Function

Our loss function (let's assume) is just $\mathcal{L} = \Sigma\left(y - \hat{y}\right)^2$. What are the partial derivatives of this function?

We have $\mathcal{L} = \Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)^2$.

Therefore:

- $\frac{\partial\mathcal{L}}{\partial w_1} = -2w_5X_1\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

- $\frac{\partial\mathcal{L}}{\partial w_2} = -2w_6X_1\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

- $\frac{\partial\mathcal{L}}{\partial w_3} = -2w_5X_2\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

- $\frac{\partial\mathcal{L}}{\partial w_4} = -2w_6X_2\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

- $\frac{\partial\mathcal{L}}{\partial w_5} = -2(w_1X_1 + w_3X_2)\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

- $\frac{\partial\mathcal{L}}{\partial w_6} = -2(w_2X_1 + w_4X_2)\Sigma\left(y - [X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)]\right)$

So the goal now should just be to nudge each of our weights in (the opposites of) these directions.

Let's first isolate each of these six weights:

In [26]:
w1 = in_hid_weights1[0]
w2 = in_hid_weights1[1]
w3 = in_hid_weights2[0]
w4 = in_hid_weights2[1]
w5 = hid_out_weights[0]
w6 = hid_out_weights[1]

Let's build an SGD function that will adjust weights after each training sample runs through the network.

In [27]:
def stoch_grad_desc(pred1=input1, pred2=input2, y=y,
              w1=w1, w2=w2, w3=w3, w4=w4,
              w5=w5, w6=w6, times_thru=1, lr=1e-4):

    for k in range(times_thru):
    
        for j in range(pred1.shape[0]):
            
            in1_val = pred1[j]
            in2_val = pred2[j]
            
            # This is stochastic gradient descent since we are updating
            # our weights *after each data point* goes through the network.
            
            sum_ = y[j] - in1_val*(w1*w5 + w2*w6) - in2_val*(w3*w5 + w4*w6)

            w5 += lr*(w1*in1_val + w3*in2_val)*sum_

            w6 += lr*(w2*in1_val + w4*in2_val)*sum_

            w1 += lr*w5*in1_val*sum_

            w2 += lr*w6*in1_val*sum_

            w3 += lr*w5*in2_val*sum_

            w4 += lr*w6*in2_val*sum_
            
            output = pred1*(w1*w5 + w2*w6) + pred2*(w3*w5 + w4*w6)
            
            if j == 0 and k == 0:
                print(f"""
                After a single data point our RMSE is {np.sqrt(mse(y, output.flatten()))}
                """)
            
        print(f"""
                After {k+1} epochs our RMSE is {np.sqrt(mse(y, output.flatten()))}
        """)
        
    return w1, w2, w3, w4, w5, w6

In [28]:
stoch_grad_desc(times_thru=5)


                After a single data point our RMSE is 131.80677685986092
                

                After 1 epochs our RMSE is 129.8450062254458
        

                After 2 epochs our RMSE is 123.33196509825842
        

                After 3 epochs our RMSE is 111.44619152943271
        

                After 4 epochs our RMSE is 104.25314828273383
        

                After 5 epochs our RMSE is 102.76034914846261
        


(array([3.74787473]),
 array([8.65770675]),
 array([0.88442709]),
 array([0.92008411]),
 array([3.63496368]),
 array([8.36568275]))

![backprop](images/ff-bb.gif)

## Easy Regression Problem

Our error has decreased with more epochs, but to illustrate the full power of our network let's see if it can find the right coefficients for an "easy" problem where there is a strong correlation between both of two input features and the target.

In [29]:
# Setting up the problem

X_easy, y_easy = make_regression(n_features=2, n_informative=2, random_state=42)

In [30]:
# Again defining weights randomly. We'll be using the same network, so we need
# six weights.

np.random.seed(42)

w_easy = np.random.rand(6)

In [31]:
# Applying our stoch_grad_desc() function

final_weights = stoch_grad_desc(pred1=X_easy[:, 0], pred2=X_easy[:, 1], y=y_easy,
         w1=w_easy[0], w2=w_easy[1], w3=w_easy[2],
         w4=w_easy[3], w5=w_easy[4], w6=w_easy[5],
         lr=4e-3, times_thru=3)
final_weights


                After a single data point our RMSE is 105.2827433708648
                

                After 1 epochs our RMSE is 0.0003058349135338318
        

                After 2 epochs our RMSE is 5.040642635748519e-09
        

                After 3 epochs our RMSE is 1.2706912599150398e-13
        


(6.556340807199361,
 10.75555705679945,
 6.914105827696129,
 7.997420739574159,
 4.334717820507707,
 5.515048597227902)

Wow! Look how small our error is after just three epochs!

### Comparing with `LinearRegression()`

We can translate these final weight values into $\beta_1$ and $\beta_2$ for a traditional linear regression $\hat{y} = \beta_1X_1 + \beta_2X_2$.

Above we calculated $\hat{y} = X_1(w_1w_5 + w_2w_6) + X_2(w_3w_5 + w_4w_6)$.

Thus we have:

- $\beta_1 = w_1w_5 + w_2w_6$, and
- $\beta_2 = w_3w_5 + w_4w_6$.

Plugging these in for our final calculated weights we have:

In [32]:
beta1 = final_weights[0]*final_weights[4] + final_weights[1]*final_weights[5]
beta2 = final_weights[2]*final_weights[4] + final_weights[3]*final_weights[5]
print(f"Our mini-NN found coefficients of {beta1} and {beta2}.")

Our mini-NN found coefficients of 87.73730719279541 and 74.07686177542038.


Let's compare these numbers with the results of `LinearRegression()`:

In [33]:
LinearRegression(fit_intercept=False).fit(X_easy, y_easy).coef_

array([87.73730719, 74.07686178])

Our little neural network, which has:
- only five neurons;
- randomly generated initial weights;
- only linear activation functions; and
- all biases set to 0

can do the same job as a linear regression after just a couple of epochs!